# APP settings
ServerAddress: "ip_address:port"

# Board settings
RefVoltage: "2.500"  # Available values: "1.250", "2.048", "2.500", "4.096"

# CAN Open settings
CanNetwork: 1
BitrateIndex: 2
Nodes:
- NodeID: <Node:1-127>
  DeviceType: 0x008C0191
  VendorID: 0x000000BE
  ProductCode: 0x00910001
  Revision: 0x00010001
  BoardSN: <Serial_number(example:2022010015)>
