CanNetwork: 1
BitrateIndex: 2
CalibFolder: "<path/to/calib_files>"
Nodes:
- NodeID: <Node:1-127>
  DeviceType: 0x008C0191
  VendorID: 0x000000BE
  ProductCode: 0x00910001
  Revision: 0x00010001
  BoardSN: <Serial_number(example:2022010015)>
